### ISSUE TITLE
can't import neptuneparams in train.py

### ISSUE THREAD

**Issue by ake020675** [AlessioGalluccio/FastFlow#1]
neptune-client has been installled

**Comment by Longxiaoze** [comment]
> neptune-client has been installled

I have the same question, just change ' import neptuneparams as nep_params' to 'import neptune as nep_params'

**Comment by AlessioGalluccio** [comment]
Hi @ake020675 @Longxiaoze,
This repository is a project of mine, and it is not completed yet. Someone added my code to paperswithcode.com, but it is not ready yet.
However, you just need to create a python file called `neptuneparams.py` and write this:
```
project = "insert your project here"
api_token="insert your token here"

```
To get these values, you need to create a project on Neptune. If you don't want to use neptune, you can comment the import and the neptune code in `train.py`

I must remind you that the model is not the model of the paper yet. I'm trying to implement it because there was no official code, but I didn't want to publish it on paperswithcode, or at least not right now.

**Comment by AlessioGalluccio** [comment]
I updated the readme with the instructions needed. Thank you very much
